package edu.hawaii.ihale.api;

/**
 * Provides a specification of the operations that should be implemented by iHale for the
 * Photovoltaics system.
 * 
 * @author Team Kohola
 */
public interface Photovoltaics {

  /**
   * To store the current energy usage of the appliance in the database. ids for the appliances,
   * e.g. tv unit: KWh
   * 
   * @param id The id of the appliance.
   * @param kwh The amount of energy consumed by the appliance.
   */
  public void storeCurrentUsage(String id, long kwh);

  /**
   * To retrieve the current usage of the given appliance.
   * 
   * @param id The id of the appliance.
   * @return The current usage of the appliance.
   */
  public long getCurrentUsage(String id);

  /**
   * To retrieve the usage of an appliance for a certain time. If want to find the average usage of
   * an appliance given a certain time. Ex. getAvgUsageAt("television", "1 AM"); will return what
   * the average usage of the television is at 1 AM.
   * 
   * @param id The appliance to find the usage of.
   * @param timeofDay The time of day to find the average usage at.
   * @return The average usage of the appliance at a given time.
   */
  public long getAvgUsageAt(String id, String timeofDay);

  /**
   * The average consumption of the house at a given time.
   * 
   * @param timeOfDay The time of day to find the average usage of the house at.
   * @return The average usage of the house at a given time.
   */
  public long getAvgUsageAt(String timeOfDay);

  /**
   * To retrieve the daily power usage of an appliance.
   * 
   * @param id The id of the appliance.
   * @return daily power usage average for id or for everything.
   */
  public long getDailyAvgUsage(String id);

  /**
   * The average usage of the house for the day.
   * 
   * @return The consumption of the house.
   */
  public long getDailyAvgUsage();

  /**
   * To retrieve the usage of the appliance for a given day.
   * 
   * @param id The id of the appliance.
   * @param date The day to retrieve usage for.
   * @return The power usage of the appliance on the date given.
   */
  public long getDateUsage(String id, String date);

  /**
   * To retrieve the usage of the house on a given day.
   * 
   * @param date The day to retrieve the usage for.
   * @return The usage of the house on the given day.
   */
  public long getDateUsage(String date);

  /**
   * Stores the generation of a solar panel.
   * 
   * @param id The id of the solar panel.
   * @param kwh The amount of energy generated by the panel.
   */
  public void storeCurrentGeneration(String id, long kwh);

  /**
   * To retrieve the current generation of the given solar panel.
   * 
   * @param id The id of the solar panel.
   * @return The current generation of the solar panel.
   */
  public long getCurrentGeneration(String id);

  /**
   * To retrieve the average generation of a solar panel for the day.
   * 
   * @param id The id of the solar panel.
   * @return The generation of the given solar panel for the day.
   */
  public long getDailyAvgGeneration(String id);

  /**
   * To retrieve the current generation of all the solar panels for the day.
   * 
   * @return The generation of the solar panels for the day.
   */
  public long getDailyAvgGeneration();

  /**
   * To retrieve the average generation of a solar panel for a given time.
   * 
   * @param id The id of the solar panel.
   * @param timeOfDay The time of day to find the average generation of the panel.
   * @return The avg generation for the solar panel or for everything if no id is passed.
   */
  public long getAvgGenerationAt(String id, String timeOfDay);

  /**
   * To retrieve the average generation of the house at a given time.
   * 
   * @param timeOfDay The time of day to find the average generation for the house.
   * @return The generation of the house for the day.
   */
  public long getAvgGenerationAt(String timeOfDay);

  // returns the power generation on the date given
  /**
   * To retrieve the current generation of the given solar panel for the given day.
   * 
   * @param id The id of the solar panel.
   * @param date The day to find the generation for.
   * @return The generation of the given solar panel for the given day.
   */
  public long getDateGeneration(String id, String date);

  /**
   * To retrieve the generation of the house for a given day.
   * 
   * @param date The day to retrieve the generation of the house.
   * @return The generation of the house for the given day.
   */
  public long getDateGeneration(String date);
}
